{{- if .Values.rbac }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: "confluent-orchestrator"
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: "confluent-orchestrator"
    helm.sh/chart: {{ include "confluent-orchestrator.chart" . }}
  name: {{ .Values.name }}
subjects:
  - kind: ServiceAccount
    name: {{ template "confluent-orchestrator.service-account" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.name }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
