{{- $_ := required "Namespace is required" .Release.Namespace }}
{{- $_ := required "Name of Orchestrator is required." .Values.name }}
{{- $webhooksPort := default 8443 .Values.webhooks.port }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: "confluent-orchestrator"
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: "cfk-blueprint"
    app.kubernetes.io/component: "confluent-orchestrator"
    helm.sh/chart: {{ include "confluent-orchestrator.chart" . }}
    version: {{ .Values.image.tag }}
  name: {{ .Values.name }}
  namespace:  {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.name }}
      app: "confluent-orchestrator"
  revisionHistoryLimit: 1
  progressDeadlineSeconds: 300
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        {{- range $key, $value := .Values.pod.annotations }}
          {{ $key }}: {{ $value | quote }}
          {{- end }}
      labels:
        app: "confluent-orchestrator"
        app.kubernetes.io/name: {{ .Values.name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        confluent-platform: "true"
        version: {{ .Values.image.tag }}
        {{- range $key, $value := .Values.pod.labels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
    spec:
      {{- if not (empty $.Values.affinity) }}
      affinity:
{{ toYaml .Values.affinity | trim | indent 8 }}
      {{- end }}
      {{- if not (empty $.Values.tolerations) }}
      tolerations:
{{ toYaml .Values.tolerations | trim | indent 6 }}
      {{- end }}
      {{- if .Values.podSecurity.enabled }}
      securityContext:
{{ toYaml .Values.podSecurity.securityContext | indent 8 }}
      {{- end }}
      containers:
      - name: core
        command: ["/opt/cpc-orchestrator"]
        args:
        - manager
        - --type=core
        - --type=cluster
        - --type=apps
        - --debug={{ .Values.debug }}
        {{- if gt (int (.Values.replicas)) 1 }}
        - --enable-leader-election
        {{- end }}
        image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{.Values.image.tag }}
        ports:
        - name: core-metrics
          containerPort: 7778
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        readinessProbe:
          httpGet:
            port: 8080
            path: /readyz
        livenessProbe:
          httpGet:
            port: 8080
            path: /healthz
        resources:
{{ toYaml .Values.resources | trim | indent 10 }}
        env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        {{- if .Values.containerSecurity.enabled }}
        securityContext:
{{ toYaml .Values.containerSecurity.securityContext | indent 10 }}
        {{- end }}
      - name: healthcheck
        command: ["/opt/cpc-orchestrator"]
        args:
        - manager
        - --type=healthcheck
        - --debug={{ .Values.debug }}
        - --metrics-bind-address=0.0.0.0:7779
        - --health-probe-bind-address=0.0.0.0:8081
  {{- if gt (int (.Values.replicas)) 1 }}
        - --enable-leader-election
        {{- end }}
        image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{.Values.image.tag }}
        ports:
        - name: hc-metrics
          containerPort: 7779
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        readinessProbe:
          httpGet:
            port: 8081
            path: /readyz
        livenessProbe:
          httpGet:
            port: 8081
            path: /healthz
        resources:
{{ toYaml .Values.resources | trim | indent 10 }}
        env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: CPC_WEBHOOKS_SERVER_NAME
            value: {{ .Values.name }}
          {{- if .Values.webhooks.tls.autoGeneratedCerts }}
          - name: CPC_WEBHOOKS_AUTOGEN_CERTS
            value: "true"
          {{- else }}
          {{- if .Values.webhooks.tls.secretRef }}
          - name: CPC_WEBHOOKS_SECRET_NAME
            value: {{ .Values.webhooks.tls.secretRef }}
          {{- end }}
          {{- if .Values.webhooks.tls.directoryPathInContainer }}
          - name: CPC_WEBHOOKS_DIRECTORY_PATH
            value: {{ .Values.webhooks.tls.directoryPathInContainer }}
          {{- end }}
          {{- end }}
          - name: CPC_WEBHOOKS_PORT
            value: {{ quote $webhooksPort }}
        {{- if .Values.containerSecurity.enabled }}
        securityContext:
{{ toYaml .Values.containerSecurity.securityContext | indent 10 }}
        {{- end }}
        {{- if (or .Values.webhooks.tls.autoGeneratedCerts .Values.webhooks.tls.secretRef) }}
        volumeMounts:
          - mountPath: /mnt/sslcerts/webhook
            name: webhook-certs
            {{- if .Values.webhooks.tls.secretRef }}
            readOnly: true
            {{- end }}
        {{- end }}
      {{- if and .Values.imagePullSecretRef (not .Values.serviceAccount.create) }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecretRef }}
      {{- end }}
      serviceAccountName: {{ template "confluent-orchestrator.service-account" . }}
      restartPolicy: Always
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- if .Values.webhooks.tls.autoGeneratedCerts }}
      volumes:
        - name: webhook-certs
          emptyDir: { }
      {{- else }}
      {{- if .Values.webhooks.tls.secretRef }}
      volumes:
        - name: webhook-certs
          secret:
            defaultMode: 420
            secretName: {{ .Values.webhooks.tls.secretRef }}
      {{- end }}
      {{- end }}
