{{- $webhooksPort := default 8443 .Values.webhooks.port }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: "confluent-orchestrator"
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: "confluent-orchestrator"
    helm.sh/chart: {{ include "confluent-orchestrator.chart" . }}
  name: {{ .Values.name }}
  namespace:  {{ .Release.Namespace }}
spec:
  ports:
    - name: core-metrics
      port: 7778
      protocol: TCP
      targetPort: 7778
    - name: hc-metrics
      port: 7779
      protocol: TCP
      targetPort: 7779
    - name: webhook
      port: {{ $webhooksPort }}
      protocol: TCP
      targetPort: {{ $webhooksPort }}
  selector:
    app: "confluent-orchestrator"
    app.kubernetes.io/name: {{ .Values.name }}
  type: ClusterIP
