{{- if .Values.serviceAccount.create -}}
apiVersion: v1
  {{- if .Values.imagePullSecretRef }}
imagePullSecrets:
  - name: {{ .Values.imagePullSecretRef }}
  {{- end }}
kind: ServiceAccount
metadata:
  labels:
    app: "confluent-agent"
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: "confluent-agent"
    helm.sh/chart: {{ include "confluent-agent.chart" . }}
  name: {{ template "confluent-agent.service-account" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
